### ISSUE TITLE
Unable to see data on TTN

### ISSUE THREAD

**Issue by jcherrabi** [Xinyuan-LilyGO/SX1302_HAL_GATEWAY#1]
Hello there,
After following your instructions I’m still not able to see my data on my TTN account! If I connect a node to TTN directly I can see the data, but as soon as I used the concentrator I see nothing and no errors in the serial either! Also I double check the config and all seems correct. I believe TTN may have change things on their platform that renders this code unusable! Can someone please try to connect one and report back!

**Comment by jaychub** [comment]
following this guide helped getting it to work on Pi 3
https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/docs/en/LilyGo_LoRa_Series_Quick_Start_On_TTN.md
